"""empty message

Revision ID: b81707756197
Revises: 9971109a4f33
Create Date: 2020-04-06 21:31:06.473987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81707756197'
down_revision = '9971109a4f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_lists', 'list_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('todos', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todo_lists', 'list_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
